export const SIGNUP_REQUESTING = "SIGNUP_REQUESTING"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_ERROR = "SIGNUP_ERROR"


export const LOGIN_REQUESTING = "LOGIN_REQUESTING"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"


export const SIGNOUT_REQUESTING = "SIGNOUT_REQUESTING"
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS"
export const SIGNOUT_ERROR = "SIGNOUT_ERROR"
